Bug fix with concat of empty lists.
jasonsjones/doubly-linked-list pull request #4
Opened 2019-02-27 00:56 UTC by bmcgary

Oops.😳  Forgot about the edge cases in my first PR (#3 ), sorry about that. This should take care of that.

2019-03-08 03:48 UTC, jasonsjones requested changes
I really need to check my notification settings 😉, I am just now seeing this.  Thanks for taking the time to follow up on your PR to fix this issue.

Made a few suggestions that should be pretty easy to update.  Let me know if you can split up the tests...if not, no worries, I can get this in and update at a later date.  Thanks again!

2019-03-08 03:48 UTC, jasonsjones commented on test/list.spec.js
> +            expect(newList.getTailNode()).to.not.equal(null);
We have a lot expectations in this test...and we are testing different cases, so maybe we should split these out to their own tests.  Maybe something like...

```
it('when empty concats a populated list', () => {
    // set up and expectations here
});
```

2019-03-08 03:48 UTC, jasonsjones commented on test/list.spec.js
> +            expect(newList.getTailNode()).to.not.exist;
This can be another separate tests. Maybe...

```
it('concats two empty lists', () => {
    // set up and expectations
});
```

2019-03-08 03:48 UTC, jasonsjones commented on test/list.spec.js
> +            expect(newList.getTailNode()).to.not.equal(null);
And another test...  I hope you get the idea.

2019-03-08 03:49 UTC, jasonsjones commented on package.json
> +    "version": "0.3.1",
Thanks for the version bump 👍

2019-03-09 17:34 UTC, bmcgary commented
Just pushed a fix. Should be good to good now! 👍

2019-03-11 14:18 UTC, jasonsjones approved these changes

2019-03-11 14:19 UTC, jasonsjones commented
Awesome!  Thanks, Blaine!

2019-03-11 14:19 UTC, merged